force-app/main/default/objects/K4B_Onboarding__c/K4B_Onboarding__c.object-meta.xml
<CustomObject>
    <description>Object to manage K4B onboarding</description>
    <label>K4B Onboarding</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>K4B Onboarding</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/K4B_Onboarding__c/fields/Business_Email__c.field-meta.xml
<CustomField>
    <fullName>Business_Email__c</fullName>
    <description>Keep business email</description>
    <label>Business Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/K4B_Onboarding__c/fields/Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email__c</fullName>
    <description>Keep contact email</description>
    <label>Contact Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/K4B_Onboarding__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <description>Used to store contact name</description>
    <label>Contact Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/K4B_Onboarding__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to store related Lead</description>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>K4B Onboarding</relationshipLabel>
    <relationshipName>K4B_Onboarding</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/K4B_Onboarding__c/fields/Planned_completion_date__c.field-meta.xml
<CustomField>
    <fullName>Planned_completion_date__c</fullName>
    <label>Planned completion date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/K4B_Onboarding__c/fields/Start_date__c.field-meta.xml
<CustomField>
    <fullName>Start_date__c</fullName>
    <description>Onboarding process start date</description>
    <label>Start date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/K4B_Onboarding__c.field-meta.xml
<CustomField>
    <fullName>K4B_Onboarding__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>K4B Onboarding</label>
    <referenceTo>K4B_Onboarding__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/K4BTriggerHandler.cls
public class K4BTriggerHandler extends TriggerHandler  {
    private Map<Id, K4B_Onboarding__c> newK4bMap;
    private Map<Id, K4B_Onboarding__c> oldK4bMap;

    public K4BTriggerHandler() {
        this.newK4bMap = (Map<Id, K4B_Onboarding__c>) Trigger.newMap;
        this.oldK4bMap = (Map<Id, K4B_Onboarding__c>) Trigger.OldMap;
    }

    public override void afterUpdate() {
        Map<Id,Lead> mapLeadbyK4bId = new Map<Id,Lead>();
        List<Id> leadIds = new List<Id>();
       List<Lead> leads = new List<Lead>();
       List<Lead> leadsToUpdate = new List<Lead>();
        for(K4B_Onboarding__c k4b :newK4bMap.values()){
            leadIds.add(k4b.Lead__c);
        }
        leads = LeadSelector.getK4BLeadByIds(leadIds);

        if(!leads.isEmpty()){
            for(Lead lead :leads){
                mapLeadbyK4bId.put(lead.K4B_Onboarding__c, lead);
            }

            for(K4B_Onboarding__c k4b :newK4bMap.values()){
                Lead lead = mapLeadbyK4bId.get(k4b.Id);
                if(k4b.Contact_Name__c != lead.LastName ||
                    k4b.Business_Email__c != lead.Company_Email__c ||
                    k4b.Contact_Email__c != lead.Email ||
                    k4b.Start_date__c != lead.Start_date__c ||
                    k4b.Planned_completion_date__c != lead.Planned_completion_date__c ||
                    k4b.Company_Name__c != lead.Company
                ){
                    lead.LastName = k4b.Contact_Name__c;
                    lead.Company_Email__c = k4b.Business_Email__c;
                    lead.Email = k4b.Contact_Email__c;
                    lead.Start_date__c = k4b.Start_date__c;
                    lead.Planned_completion_date__c = k4b.Planned_completion_date__c;
                    lead.Company = k4b.Company_Name__c;
                    leadsToUpdate.add(lead);
                }
            } 
            if(!leadsToUpdate.isEmpty()){
                update leadsToUpdate;
            }
        }
    }
}