force-app/main/default/objects/K4B_Onboarding__c/K4B_Onboarding__c.object-meta.xml
<CustomObject>
    <description>Object to manage K4B onboarding</description>
    <label>K4B Onboarding</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>K4B Onboarding</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/K4B_Onboarding__c/fields/Planned_completion_date__c.field-meta.xml
<CustomField>
    <fullName>Planned_completion_date__c</fullName>
    <label>Planned completion date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/K4B_Onboarding__c/fields/Start_date__c.field-meta.xml
<CustomField>
    <fullName>Start_date__c</fullName>
    <description>Onboarding process start date</description>
    <label>Start date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/K4B_Onboarding__c.field-meta.xml
<CustomField>
    <fullName>K4B_Onboarding__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>K4B Onboarding</label>
    <referenceTo>K4B_Onboarding__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LeadSelector.cls
public class LeadSelector {
    
    public static List<Lead> getK4BLeadByIds(List<Id> leadIds){
        List<Lead> leads = new List<Lead>();
        if(leadIds.isEmpty()){
            return leads;
        }
        leads = [SELECT Id,LastName,K4B_Onboarding__c,Company_Email__c,Company,Email,Start_date__c,Planned_completion_date__c FROM Lead WHERE Id IN :leadIds AND K4B_Onboarding__c != null];
        return leads;
    }

}